repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.3
  hooks:
    # Run the linter.
    - id: ruff-check
      name: ruff clean whitespace
      args: [
              "--fix",
              "--select", "C4,FA102,F821,ISC,PIE794,PIE796,PIE8,TC004,W,YTT"
            ]
    - id: ruff-check
      args: [
              "--exit-zero",
            ]
    # Run the formatter.
    - id: ruff-format
      args: ["-v"]