name: Publish Python package to PyPI

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    build:
        name: Build distribution
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              #with:
              #  fetch-depth: 0  # 0 fetches all history

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Install build tools
              run: python -m pip install --upgrade pip build

            - name: Build distributions
              run: python -m build

            - name: Store the distribution packages
              uses: actions/upload-artifact@v4
              with:
                name: python-package-distributions
                path: dist/
    publish:
        needs:
            - build
        runs-on: ubuntu-latest
        environment:
            name: pypi
        permissions:
            id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
            - name: Download all the dists
              uses: actions/download-artifact@v4
              with:
                name: python-package-distributions
                path: dist/

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # releases/v1
              with:
                verbose: true
                repository-url: https://upload.pypi.org/legacy/
