# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pyright (minimal)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      id: setup_python
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: setup.py
    - run: echo 'Dependency Cache hit ${{ steps.setup_python.outputs.cache-hit }}'
    - name: Install dependencies
      run: |
        pip install . pyright
    - name: Run pyright minimally
      run: pyright -p .basic_pyright_check.json